import type { MusicBed, MusicProvider, MusicRequest } from '@/lib/providers/types';
import { writeWav } from '@/lib/providers/voice/wav';
import { seededRandom, stableHash } from '@/lib/util/hash';

/**
 * Procedural ambient bed.
 *
 * Not a stand-in for a licensed track — it is a synthesised pad designed to do
 * one job well: sit under narration without competing with it. Everything above
 * ~1.2 kHz is rolled off, which is where speech intelligibility lives, and the
 * whole bed is generated below the target so the ducking has something to duck.
 *
 * Its provenance is recorded like any other asset, so nobody can mistake it for
 * a library cue.
 */

const SAMPLE_RATE = 48_000;

/** A minor, i – VI – III – VII. Slow, unresolved, and out of the way. */
const PROGRESSION: number[][] = [
  [110.00, 164.81, 261.63], // Am
  [ 87.31, 130.81, 220.00], // F
  [130.81, 196.00, 329.63], // C
  [ 98.00, 146.83, 246.94], // G
];

const CHORD_SECONDS = 8;

export class ProceduralMusicProvider implements MusicProvider {
  readonly name = 'procedural-ambient-pad@1';
  readonly isLive = false;

  async generate(req: MusicRequest): Promise<MusicBed> {
    const rnd = seededRandom(stableHash(`${req.mood}:${req.seed}`));
    const n = Math.max(1, Math.round(req.durationSeconds * SAMPLE_RATE));
    const buf = new Float32Array(n);

    // Slight per-run detune, seeded, so two beds are not phase-identical.
    const detune = 1 + (rnd() - 0.5) * 0.002;

    for (let i = 0; i < n; i += 1) {
      const t = i / SAMPLE_RATE;
      const chordIndex = Math.floor(t / CHORD_SECONDS) % PROGRESSION.length;
      const chord = PROGRESSION[chordIndex]!;
      const localT = (t % CHORD_SECONDS) / CHORD_SECONDS;

      // Raised-cosine envelope per chord so pads cross-fade rather than cut.
      const env = 0.5 - 0.5 * Math.cos(2 * Math.PI * localT);

      let v = 0;
      for (const [voice, f] of chord.entries()) {
        const weight = voice === 0 ? 1 : voice === 1 ? 0.55 : 0.35;
        v += Math.sin(2 * Math.PI * f * t) * weight;
        v += Math.sin(2 * Math.PI * f * detune * t) * weight * 0.6;   // width
        v += Math.sin(2 * Math.PI * f * 2 * t) * weight * 0.10;       // a little air
      }
      buf[i] = v * env * 0.08;
    }

    // Two one-pole low-passes in series: keep the bed out of the speech band.
    lowPass(buf, 1200);
    lowPass(buf, 2400);

    // Fade the ends so the bed does not click in or out against the video.
    const fade = Math.min(SAMPLE_RATE * 2, Math.floor(n / 4));
    for (let i = 0; i < fade; i += 1) {
      const g = 0.5 - 0.5 * Math.cos((Math.PI * i) / fade);
      buf[i] = (buf[i] ?? 0) * g;
      buf[n - 1 - i] = (buf[n - 1 - i] ?? 0) * g;
    }

    let peak = 0;
    for (const v of buf) { const a = Math.abs(v); if (a > peak) peak = a; }
    const scale = peak > 0 ? 0.35 / peak : 1;

    const pcm = new Int16Array(n);
    for (let i = 0; i < n; i += 1) {
      pcm[i] = Math.round(Math.max(-1, Math.min(1, (buf[i] ?? 0) * scale)) * 32_767);
    }

    return {
      wav: writeWav(pcm, SAMPLE_RATE),
      durationSeconds: n / SAMPLE_RATE,
      generator: this.name,
      title: `Ambient pad (${req.mood})`,
      licence: 'Generated by this repository. No third-party rights attach.',
      provenance: `${this.name} · seed ${req.seed} · ${req.mood} · A minor i-VI-III-VII, ${CHORD_SECONDS}s per chord`,
    };
  }
}

/** One-pole low-pass, in place. Deterministic and cheap. */
function lowPass(buf: Float32Array, cutoffHz: number): void {
  const rc = 1 / (2 * Math.PI * cutoffHz);
  const dt = 1 / SAMPLE_RATE;
  const alpha = dt / (rc + dt);
  let prev = 0;
  for (let i = 0; i < buf.length; i += 1) {
    prev += alpha * ((buf[i] ?? 0) - prev);
    buf[i] = prev;
  }
}
